version: "3.9"
services:
    nginx:
        container_name: nginx
        build:
            context: docker/nginx
        ports:
            - "80:80"
        volumes:
            - ./:/app
        depends_on:
            - php-fpm

    php-fpm:
        container_name: php-fpm
        build:
            context: docker/php-fpm
        volumes:
            - ./:/app

    php-cli:
        container_name: php-cli
        build:
            context: docker/php-cli
        volumes:
            - ./:/app
